/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jib.builder;

import com.beust.jcommander.JCommander;
import com.github.dockerjava.core.DockerConfigFile;
import com.github.dockerjava.core.dockerfile.*;

import java.io.File;
import java.io.IOException;


public class App {

    public static void main(String[] args) throws IOException {
        Args params = new Args();
        String[] argv = {};

        JCommander jc=new JCommander(params);
        try {
            jc.setProgramName("jib-img");
            jc.parse(argv);

        } catch (com.beust.jcommander.ParameterException e) {
            System.out.println(e.getMessage());
           jc.usage();
           System.exit(0);
        }

        Image img = new Image();

        img.build(params);


    }

}
